language: node_js
node_js:
  - "9.5.0"

cache: yarn

script:
  - hexo clean
  - hexo generate

after_script:
  - cd ./public
  - git init
  - git config user.name "erwai"
  - git config user.email "jean8389she@gmail.com"
  - git add .
  - git commit -m "site updated"
  - git push --quiet --force https://$GH_TOKEN@github.com/erwai/erwai.github.io.git master

branches:
  only:
  - contents
  except:
  - master
