language: node_js

os: osx

sudo: required

node_js:
  - "9.5.0"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "erwai"
  - git config user.email "fwlnnb@gmail.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

branches:
  only:
  - contents
  except:
  - master
